package interactiveepidemiologytool;

public class IET extends javax.swing.JFrame {

    public IET() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        popSlider = new javax.swing.JSlider();
        popCurrent = new javax.swing.JLabel();
        popLabel = new javax.swing.JLabel();
        infectedSlider = new javax.swing.JSlider();
        infectedCurrent = new javax.swing.JLabel();
        infectLabel = new javax.swing.JLabel();
        timeSlider = new javax.swing.JSlider();
        timeCurrent = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        covidButton = new javax.swing.JRadioButton();
        fluButton = new javax.swing.JRadioButton();
        vaccineCurrent = new javax.swing.JLabel();
        vaccineLabel = new javax.swing.JLabel();
        vaccineSlider = new javax.swing.JSlider();
        quarantineCurrent = new javax.swing.JLabel();
        quarantineLabel = new javax.swing.JLabel();
        quarantineSlider = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        instructions = new javax.swing.JTextArea();
        covidButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Start!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        popSlider.setMaximum(100000);
        popSlider.setMinimum(10000);
        popSlider.setToolTipText("");
        popSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                popSliderStateChanged(evt);
            }
        });

        popCurrent.setLabelFor(popSlider);
        popCurrent.setText("10000");
        popCurrent.setToolTipText("");

        popLabel.setLabelFor(popSlider);
        popLabel.setText("Population");

        infectedSlider.setMinimum(1);
        infectedSlider.setToolTipText("");
        infectedSlider.setValue(1);
        infectedSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                infectedSliderStateChanged(evt);
            }
        });

        infectedCurrent.setLabelFor(infectedSlider);
        infectedCurrent.setText("1");
        infectedCurrent.setToolTipText("");

        infectLabel.setLabelFor(infectedSlider);
        infectLabel.setText("Infected");

        timeSlider.setMaximum(150);
        timeSlider.setMinimum(50);
        timeSlider.setToolTipText("");
        timeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                timeSliderStateChanged(evt);
            }
        });

        timeCurrent.setLabelFor(timeSlider);
        timeCurrent.setText("50");
        timeCurrent.setToolTipText("");

        timeLabel.setLabelFor(timeSlider);
        timeLabel.setText("Timeframe");

        buttonGroup2.add(covidButton);
        covidButton.setText("Covid-19");
        covidButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                covidButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(fluButton);
        fluButton.setText("Influenza");
        fluButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fluButtonActionPerformed(evt);
            }
        });

        vaccineCurrent.setLabelFor(vaccineSlider);
        vaccineCurrent.setText("0");
        vaccineCurrent.setToolTipText("");

        vaccineLabel.setLabelFor(infectedSlider);
        vaccineLabel.setText("Percent of population that is vaccinated");

        vaccineSlider.setToolTipText("");
        vaccineSlider.setValue(0);
        vaccineSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                vaccineSliderStateChanged(evt);
            }
        });

        quarantineCurrent.setLabelFor(quarantineSlider);
        quarantineCurrent.setText("0");
        quarantineCurrent.setToolTipText("");

        quarantineLabel.setLabelFor(quarantineSlider);
        quarantineLabel.setText("Percent of population that quarantine when displaying symptoms");

        quarantineSlider.setToolTipText("");
        quarantineSlider.setValue(0);
        quarantineSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                quarantineSliderStateChanged(evt);
            }
        });

        instructions.setEditable(false);
        instructions.setColumns(20);
        instructions.setRows(5);
        instructions.setText("Welcome to our interactive epidemiology tool!\n\nTo get started please select a disease you wish to simulate.\nAfter that please selection the parameters and safeguards you\nwould like to simulate for that disease.\n\nWhen you are happy with your selection please hit start.");
        jScrollPane1.setViewportView(instructions);

        buttonGroup2.add(covidButton1);
        covidButton1.setSelected(true);
        covidButton1.setText("Bubonic plague");
        covidButton1.setActionCommand("Bubonic plague");
        covidButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                covidButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quarantineLabel)
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(timeCurrent)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fluButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 554, Short.MAX_VALUE)
                                        .addComponent(infectedCurrent)))
                                .addGap(105, 105, 105))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(popLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(popSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(timeLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(timeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(infectLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(infectedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(covidButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(popCurrent)
                                .addGap(88, 88, 88))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(covidButton)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quarantineSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vaccineSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vaccineLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(quarantineCurrent, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(vaccineCurrent, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(98, 98, 98)))))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(vaccineLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vaccineSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vaccineCurrent)
                        .addGap(28, 28, 28)
                        .addComponent(quarantineLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quarantineSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quarantineCurrent)
                .addGap(33, 33, 33)
                .addComponent(covidButton)
                .addGap(18, 18, 18)
                .addComponent(fluButton)
                .addGap(18, 18, 18)
                .addComponent(covidButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infectedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infectLabel))
                .addGap(10, 10, 10)
                .addComponent(infectedCurrent)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(popSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(popLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(popCurrent)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeCurrent)
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // TODO: Implement observer
    // I believe this is the data that requires implementing an observer for
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SEIR epidemic = new SEIR();
        epidemic.setPop(popSlider.getValue());
        epidemic.setInfected(infectedSlider.getValue());
        epidemic.setTimeframe(timeSlider.getValue());
        
        // TODO: From what I have seen most SIR/SEIR models guess good values
        // Lets try to research some better values
        if(covidButton.isSelected()){             
            epidemic.setInfectionRate(epidemic.setRateCovid(vaccineSlider.getValue(), quarantineSlider.getValue()));     
            epidemic.setRecovery(1.0/12.0);
            epidemic.setIncubation(1.0/2.0);
        }
        else if(fluButton.isSelected()){    // These are all bad guesses, need fixing
            epidemic.setInfectionRate(epidemic.setRateFlu(vaccineSlider.getValue(), quarantineSlider.getValue()));
            epidemic.setRecovery(1.0/7.0);
            epidemic.setIncubation(1.0/2.0);
        }
        
        epidemic.simulate();
        System.out.println(epidemic.S);
        System.out.println(epidemic.E);
        System.out.println(epidemic.I);
        System.out.println(epidemic.R);
        
        ResultsPage results = new ResultsPage(new IET(), true, 
                epidemic.S.get(timeSlider.getValue()).toString(),
                epidemic.E.get(timeSlider.getValue()).toString(),
                epidemic.I.get(timeSlider.getValue()).toString(),
                epidemic.R.get(timeSlider.getValue()).toString());
        results.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void popSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_popSliderStateChanged
        popCurrent.setText(""+popSlider.getValue());
    }//GEN-LAST:event_popSliderStateChanged

    private void infectedSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_infectedSliderStateChanged
        infectedCurrent.setText(""+infectedSlider.getValue());
    }//GEN-LAST:event_infectedSliderStateChanged

    private void timeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_timeSliderStateChanged
        timeCurrent.setText(""+timeSlider.getValue());
    }//GEN-LAST:event_timeSliderStateChanged

    private void covidButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_covidButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_covidButtonActionPerformed

    private void fluButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fluButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fluButtonActionPerformed

    private void vaccineSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_vaccineSliderStateChanged
        vaccineCurrent.setText(""+vaccineSlider.getValue());
    }//GEN-LAST:event_vaccineSliderStateChanged

    private void quarantineSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_quarantineSliderStateChanged
        quarantineCurrent.setText(""+quarantineSlider.getValue());
    }//GEN-LAST:event_quarantineSliderStateChanged

    private void covidButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_covidButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_covidButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IET.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IET.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IET.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IET.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IET().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton covidButton;
    private javax.swing.JRadioButton covidButton1;
    private javax.swing.JRadioButton fluButton;
    private javax.swing.JLabel infectLabel;
    private javax.swing.JLabel infectedCurrent;
    private javax.swing.JSlider infectedSlider;
    private javax.swing.JTextArea instructions;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel popCurrent;
    private javax.swing.JLabel popLabel;
    private javax.swing.JSlider popSlider;
    private javax.swing.JLabel quarantineCurrent;
    private javax.swing.JLabel quarantineLabel;
    private javax.swing.JSlider quarantineSlider;
    private javax.swing.JLabel timeCurrent;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JSlider timeSlider;
    private javax.swing.JLabel vaccineCurrent;
    private javax.swing.JLabel vaccineLabel;
    private javax.swing.JSlider vaccineSlider;
    // End of variables declaration//GEN-END:variables
}
