/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interactiveepidemiologytool;

public class ResultsPage extends javax.swing.JDialog {

    private IET iet;
    
    public ResultsPage(IET iet, boolean modal, 
            String s, String e, String i, String r) {
        super(iet, modal);
        initComponents();
        susceptibleValue.setText(s);
        exposedValue.setText(e);
        infectedValue.setText(i);
        recoveredValue.setText(r);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        susceptibleValue = new javax.swing.JLabel();
        sDescription = new javax.swing.JLabel();
        exposedValue = new javax.swing.JLabel();
        eDescription = new javax.swing.JLabel();
        infectedValue = new javax.swing.JLabel();
        iDescription = new javax.swing.JLabel();
        recoveredValue = new javax.swing.JLabel();
        rDescription = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        susceptibleValue.setText("Susceptible");

        sDescription.setLabelFor(susceptibleValue);
        sDescription.setText("S Array Result, Not-sick and Not-dead");

        exposedValue.setText("Exposed");

        eDescription.setLabelFor(exposedValue);
        eDescription.setText("E Array Ending Value, Exposed to virus");

        infectedValue.setText("Infected");

        iDescription.setLabelFor(infectedValue);
        iDescription.setText("I Array Ending Value, Infected by virus");

        recoveredValue.setText("Recovered");

        rDescription.setLabelFor(recoveredValue);
        rDescription.setText("R Array Result, Recovered or dead");

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(exitButton)
                        .addGap(205, 205, 205))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eDescription)
                            .addComponent(rDescription)
                            .addComponent(iDescription)
                            .addComponent(sDescription)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(recoveredValue)
                                    .addComponent(infectedValue)
                                    .addComponent(exposedValue)
                                    .addComponent(susceptibleValue))))
                        .addGap(142, 142, 142))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(susceptibleValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sDescription)
                .addGap(18, 18, 18)
                .addComponent(exposedValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eDescription)
                .addGap(28, 28, 28)
                .addComponent(infectedValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iDescription)
                .addGap(18, 18, 18)
                .addComponent(recoveredValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rDescription)
                .addGap(34, 34, 34)
                .addComponent(exitButton)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ResultsPage dialog = new ResultsPage(new IET(), true, 
                        new String(), new String(), new String(), new String());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eDescription;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel exposedValue;
    private javax.swing.JLabel iDescription;
    private javax.swing.JLabel infectedValue;
    private javax.swing.JLabel rDescription;
    private javax.swing.JLabel recoveredValue;
    private javax.swing.JLabel sDescription;
    private javax.swing.JLabel susceptibleValue;
    // End of variables declaration//GEN-END:variables
}
