package View;

import Model.PopulationModel;
import java.awt.BorderLayout;
import org.jfree.chart.ChartPanel;

public class ResultsPage extends javax.swing.JDialog {
    
    public ResultsPage(MainPage iet, boolean modal, 
            PopulationModel epidemic, int timeframe) {
        super(iet, modal);
        initComponents();
        susceptibleValue.setText(epidemic.S.get(timeframe).toString());
        exposedValue.setText(epidemic.E.get(timeframe).toString());
        infectedValue.setText(epidemic.I.get(timeframe).toString());
        recoveredValue.setText(epidemic.R.get(timeframe).toString());
        
        ChartSimulation chart = new ChartSimulation();
        chart.makeChart(epidemic, timeframe);
        
        ChartPanel panel = chart.makeChart(epidemic, timeframe);
        
        chartPanel.add(panel, BorderLayout.CENTER);
        PieChart pieChart = new PieChart(epidemic, timeframe);
        pieChart.chartPanel.setVisible(true);
        piePanel.add(pieChart.chartPanel, BorderLayout.CENTER);
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        susceptibleValue = new javax.swing.JLabel();
        sDescription = new javax.swing.JLabel();
        exposedValue = new javax.swing.JLabel();
        eDescription = new javax.swing.JLabel();
        infectedValue = new javax.swing.JLabel();
        iDescription = new javax.swing.JLabel();
        recoveredValue = new javax.swing.JLabel();
        rDescription = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        chartPanel = new javax.swing.JPanel();
        piePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1090, 623));

        susceptibleValue.setText("Susceptible");

        sDescription.setLabelFor(susceptibleValue);
        sDescription.setText("S Array Result, Not-sick and Not-dead");

        exposedValue.setText("Exposed");

        eDescription.setLabelFor(exposedValue);
        eDescription.setText("E Array Ending Value, Exposed to virus");

        infectedValue.setText("Infected");

        iDescription.setLabelFor(infectedValue);
        iDescription.setText("I Array Ending Value, Infected by virus");

        recoveredValue.setText("Recovered");

        rDescription.setLabelFor(recoveredValue);
        rDescription.setText("R Array Result, Recovered or dead");

        exitButton.setText("Return");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        chartPanel.setLayout(new java.awt.BorderLayout());

        piePanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(piePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                    .addComponent(chartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eDescription)
                    .addComponent(rDescription)
                    .addComponent(iDescription)
                    .addComponent(sDescription)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recoveredValue)
                            .addComponent(infectedValue)
                            .addComponent(exposedValue)
                            .addComponent(susceptibleValue)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(susceptibleValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sDescription)
                        .addGap(18, 18, 18)
                        .addComponent(exposedValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eDescription)
                        .addGap(28, 28, 28)
                        .addComponent(infectedValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iDescription)
                        .addGap(18, 18, 18)
                        .addComponent(recoveredValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rDescription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                        .addComponent(exitButton)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(piePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(int timeframe) {
                ResultsPage dialog = new ResultsPage(new MainPage(), true,
                new PopulationModel(), timeframe);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }

            @Override
            public void run() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chartPanel;
    private javax.swing.JLabel eDescription;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel exposedValue;
    private javax.swing.JLabel iDescription;
    private javax.swing.JLabel infectedValue;
    private javax.swing.JPanel piePanel;
    private javax.swing.JLabel rDescription;
    private javax.swing.JLabel recoveredValue;
    private javax.swing.JLabel sDescription;
    private javax.swing.JLabel susceptibleValue;
    // End of variables declaration//GEN-END:variables
}
