package interactiveepidemiologytool;

public class AboutModelPage extends javax.swing.JDialog {

    public AboutModelPage(MainPage iet, boolean modal) {
        super(iet, modal);
        initComponents();
        Intro.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Intro = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        Intro.setEditable(false);
        Intro.setColumns(20);
        Intro.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        Intro.setRows(5);
        Intro.setText("Thank you for your interest in our tool! Epidemiology is the study of how diseases affect a group \nof people. Both in the spread of the disease and the impact of the disease on the group of people.\nTo study how diseases spread simulations are used to model populations. SEIR is one of many \nmodels used to simulation a population. SEIR stands for: Susceptible Exposed Infected \nRecovered.\nEach component represents a portion of a population of people:\nSusceptible - People who are at risk of being exposed to a disease\nExposed - People who have been exposed but are not showing symptoms\nInfected - People who demonstrate symptoms\nRecovered - People who have overcome the disease or died\nThe model calculates the size of each population once per day.");
        jScrollPane1.setViewportView(Intro);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 10, 470, 180);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interactiveepidemiologytool/th-1902095236.jpeg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 480, 260);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutModelPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutModelPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutModelPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutModelPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AboutModelPage dialog = new AboutModelPage(new MainPage(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Intro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
